#!/usr/bin/env bash

# prevent bug when using nvm (https://github.com/nvm-sh/nvm)
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
    . "$NVM_DIR/nvm.sh"
fi

# check commit message with commitlint
pnpm dlx commitlint --edit $1
